In [1]:
import pandas as pd
df=pd.read_csv("decision_tree.csv")

In [2]:
df.head()

    Outlook Temperature Humidity    Wind PlayTennis
0     sunny         hot     high    weak         no
1     sunny         hot     high  strong         no
2  overcast         hot     high    weak        yes
3      rain        mild     high    weak        yes
4      rain        cool   normal    weak        yes

In [4]:
target=df["PlayTennis"]
df.drop("PlayTennis",axis=1)

     Outlook Temperature Humidity    Wind
0      sunny         hot     high    weak
1      sunny         hot     high  strong
2   overcast         hot     high    weak
3       rain        mild     high    weak
4       rain        cool   normal    weak
5       rain        cool   normal  strong
6   overcast        cool   normal  strong
7      sunny        mild     high    weak
8      sunny        cool   normal    weak
9       rain        mild   normal    weak
10     sunny        mild   normal  strong
11  overcast        mild     high  strong
12  overcast         hot   normal    weak
13      rain        mild     high  strong

In [5]:
target

0      no
1      no
2     yes
3     yes
4     yes
5      no
6     yes
7      no
8     yes
9     yes
10    yes
11    yes
12    yes
13     no
Name: PlayTennis, dtype: object

In [6]:
from sklearn.preprocessing import LabelEncoder

In [7]:
le_outlook=LabelEncoder()
le_temp=LabelEncoder()
le_humidity=LabelEncoder()
le_wind=LabelEncoder()

In [8]:
df["le_outlook"]=le_outlook.fit_transform(df["Outlook"])
df["le_temp"]=le_temp.fit_transform(df["Temperature"])
df["le_humidity"]=le_humidity.fit_transform(df["Humidity"])
df["le_wind"]=le_wind.fit_transform(df["Wind"])

In [9]:
df

,Outlook,Temperature,Humidity,Wind,PlayTennis,le_outlook,le_temp,le_humidity,le_wind
0,sunny,hot,high,weak,no,2,1,0,1
1,sunny,hot,high,strong,no,2,1,0,0
2,overcast,hot,high,weak,yes,0,1,0,1
3,rain,mild,high,weak,yes,1,2,0,1
4,rain,cool,normal,weak,yes,1,0,1,1
5,rain,cool,normal,strong,no,1,0,1,0
6,overcast,cool,normal,strong,yes,0,0,1,0
7,sunny,mild,high,weak,no,2,2,0,1
8,sunny,cool,normal,weak,yes,2,0,1,1
9,rain,mild,normal,weak,yes,1,2,1,1
10,sunny,mild,normal,strong,yes,2,2,1,0
11,overcast,mild,high,strong,yes,0,2,0,0
12,overcast,hot,normal,weak,yes,0,1,1,1
13,rain,mild,high,strong,no,1,2,0,0

In [12]:
df_new=df.drop(["Outlook","Temperature","Humidity","Wind","PlayTennis"],axis=1)

In [13]:
le_target=LabelEncoder()

In [14]:
df3=le_target.fit_transform(target)

In [17]:
from sklearn import tree
model=tree.DecisionTreeClassifier()
model.fit(df_new,df3)

DecisionTreeClassifier()

In [18]:
model.predict([[2,0,1,1]])

/home/kishore/miniconda3/envs/ml310/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([1])

In [21]:
model.get_n_leaves()

7

In [23]:
model.score